We seem to be having an issue executing DHCP on XCP-ng server that is hosting the DHCP server in a VM.

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -129,7 +129,7 @@ update_plugin() {
 
     # Install plugin
     local uri cmd res
-    uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
+    uri="scp://${XEN_MGT}:22${plugin_dir}/${file_name}"
     if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
       logError "Failed to upload start plugin"
       return 1
@@ -165,7 +165,7 @@ qnap_exec() {
   local __ssh_res=${1}
   shift
 
-  nu_ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" "22" "${@}"
+  nu_ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" "22" "${@}"
   return $?
 }
 
@@ -203,21 +203,21 @@ configure_network() {
     return 1
   fi
 
-  # Wait for the device to appear on the network
-  if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
-    return 1
-  fi
-  if ! nu_wait_ping "${XEN_HOST}" "30"; then
-    return 1
-  fi
+  # # Wait for the device to appear on the network
+  # if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
+  #   return 1
+  # fi
+  # if ! nu_wait_ping "${XEN_HOST}" "30"; then
+  #   return 1
+  # fi
 
-  # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
-  if ! xe_create_connection "${XEN_HOST}"; then
-    logFatal "Failed to connect to demers-qnap"
-    return 1
-  else
-    logInfo "Connected successfully to demers-qnap"
-  fi
+  # # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
+  # if ! xe_create_connection "${XEN_HOST}"; then
+  #   logFatal "Failed to connect to demers-qnap"
+  #   return 1
+  # else
+  #   logInfo "Connected successfully to demers-qnap"
+  # fi
 
   # Reconfigure the management interface
   # For some reasons, even tho the command works fine, it returns 1
