Replace stop plugins with a shutdown of all local VMs Delete prior plugins during update

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -157,8 +157,16 @@ update_plugin() {
     return 1
   fi
 
+  # Remove all prior plugins
+  local cmd res
+  cmd=(rm -rf "${plugin_dir}/*")
+  if ! qnap_exec res "${cmd[@]}"; then
+    logError "Failed to remove prior plugins"
+    return 1
+  fi
+
   # Configure the plugin
-  local plug_file uri cmd res
+  local plug_file uri
   for plug_file in "${files[@]}"; do
     file_name=$(basename "${plug_file}")
     logInfo "Installing plugin: ${file_name}"
@@ -174,7 +182,7 @@ update_plugin() {
     fi
 
     # Install plugin
-    uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
+    uri="scp://${XEN_MGT}:22${plugin_dir}/${file_name}"
     if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_USER}" "${XEN_PWD}" "force"; then
       logError "Failed to upload start plugin"
       return 1
@@ -213,7 +221,7 @@ qnap_exec() {
   local __ssh_res=${1}
   shift
 
-  ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" "22" "${@}"
+  ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" "22" "${@}"
   return $?
 }
 
@@ -251,21 +259,21 @@ configure_network() {
     return 1
   fi
 
-  # Wait for the device to appear on the network
-  if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
-    return 1
-  fi
-  if ! nu_wait_ping "${XEN_HOST}" "30"; then
-    return 1
-  fi
+  # # Wait for the device to appear on the network
+  # if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
+  #   return 1
+  # fi
+  # if ! nu_wait_ping "${XEN_HOST}" "30"; then
+  #   return 1
+  # fi
 
-  # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
-  if ! xe_create_connection "${XEN_HOST}"; then
-    logError "Failed to connect to demers-qnap"
-    return 1
-  else
-    logInfo "Connected successfully to demers-qnap"
-  fi
+  # # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
+  # if ! xe_create_connection "${XEN_HOST}"; then
+  #   logError "Failed to connect to demers-qnap"
+  #   return 1
+  # else
+  #   logInfo "Connected successfully to demers-qnap"
+  # fi
 
   # Reconfigure the management interface
   # For some reasons, even tho the command works fine, it returns 1
diff --git a/src/bootstrap/00-baremetal/demers-sol/setup b/src/bootstrap/00-baremetal/demers-sol/setup
--- a/src/bootstrap/00-baremetal/demers-sol/setup
+++ b/src/bootstrap/00-baremetal/demers-sol/setup
@@ -151,8 +151,16 @@ install_pugins() {
   plugin_dir="${SOL_HOME}/${plugin_dir}"
   logInfo "Plugin directory: ${plugin_dir}"
 
+  # Remove all prior plugins
+  local cmd res
+  cmd=(rm -rf "${plugin_dir}/*")
+  if ! sol_exec res "${cmd[@]}"; then
+    logError "Failed to remove prior plugins"
+    return 1
+  fi
+
   # Configure the plugin
-  local plug_file uri cmd res
+  local plug_file uri
   # shellcheck disable=SC2066
   for plug_file in "${files[@]}"; do
     file_name=$(basename "${plug_file}")
@@ -207,7 +215,7 @@ connect_qnap_to_sol() {
 
   # Get qnap identity
   local qnap_id
-  if ! ssh_identity_create qnap_id "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" 22; then
+  if ! ssh_identity_create qnap_id "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" 22; then
     logError "Failed to create demers identity"
     return 1
   fi
