Add plugin execution TODO: Remove commented code

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -91,11 +91,15 @@ update_plugin() {
 
   # Find plugin files
   local files=()
+  local start_plugins=()
   local file
   for file in "${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap/plugins/"*; do
     # Only keep files that start with start_, stop_ and power_
     if [[ $(basename "${file}") =~ ^(start_|stop_|power_).* ]]; then
       files+=("${file}")
+    fi
+    if [[ $(basename "${file}") =~ ^start_.* ]]; then
+      start_plugins+=("${file}")
     fi
   done
 
@@ -188,12 +192,15 @@ update_plugin() {
     fi
   done
 
-  # Exexute the plugin to start the VM
-  cmd=("${plugin_dir}/$(basename "${start_file}")")
-  if ! qnap_exec res "${cmd[@]}"; then
-    logError "Failed to execute start plugin"
-    return 1
-  fi
+  # Start the plugins
+  # for plug_file in "${start_plugins[@]}"; do
+  #   file_name=$(basename "${plug_file}")
+  #   logInfo "Starting plugin: ${file_name}"
+  #   if ! qnap_exec res "${plugin_dir}/${file_name}"; then
+  #     logError "Failed to start plugin"
+  #     return 1
+  #   fi
+  # done
 
   return 0
 }
@@ -207,7 +214,7 @@ qnap_exec() {
   local __ssh_res=${1}
   shift
 
-  nu_ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" "22" "${@}"
+  ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" "22" "${@}"
   return $?
 }
 
@@ -246,9 +253,9 @@ configure_network() {
   fi
 
   # Wait for the device to appear on the network
-  if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
-    return 1
-  fi
+  # if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
+  #   return 1
+  # fi
   # if ! nu_wait_ping "${XEN_HOST}" "30"; then
   #   return 1
   # fi
diff --git a/src/bootstrap/00-baremetal/demers-sol/setup b/src/bootstrap/00-baremetal/demers-sol/setup
--- a/src/bootstrap/00-baremetal/demers-sol/setup
+++ b/src/bootstrap/00-baremetal/demers-sol/setup
@@ -126,11 +126,15 @@ configure_htpc() {
 install_pugins() {
   # Find plugin files
   local files=()
+  local start_files=()
   local file
   for file in "${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-sol/plugins/"*; do
     # Only keep files that start with start_, stop_ and power_
     if [[ $(basename "${file}") =~ ^(start_|stop_|power_).* ]]; then
       files+=("${file}")
+    fi
+    if [[ $(basename "${file}") =~ ^start_.* ]]; then
+      start_files+=("${file}")
     fi
   done
 
@@ -182,6 +186,18 @@ install_pugins() {
       return 1
     fi
   done
+
+  # Start the plugins
+  for plug_file in "${start_files[@]}"; do
+    file_name=$(basename "${plug_file}")
+    logInfo "Starting plugin: ${file_name}"
+    if ! qnap_exec res "${plugin_dir}/${file_name}"; then
+      logError "Failed to start plugin"
+      return 1
+    fi
+  done
+
+  return 0
 }
 
 connect_qnap_to_sol() {
