- Delete temp file - Force upload

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -128,10 +128,14 @@ update_plugin() {
   # Install plugin
   local uri cmd res
   uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
-  if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}"; then
+  if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
     logError "Failed to upload start plugin"
     return 1
+  elif ! rm "${tmp_file}"; then
+    logError "Failed to remove temporary file"
+    return 1
   fi
+
   # Make the plugin executable
   cmd=(chmod +x "${plugin_dir}/${file_name}")
   if ! qnap_exec res "${cmd[@]}"; then
