Support multiple plugins on qnap and sol SOL now configures HTPC SOL now can be accessed from QNAP Ready to test startup/shutdown I will probably miss a few environment variables during plugin installation.

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -20,13 +20,13 @@
 
 setup() {
   if ! sdq_config; then
-    logFatal "Failed to configure"
+    logError "Failed to configure"
     return 1
   fi
 
   # Create the pool if it doesn't exist already
   if ! xe_pool_create "${POOL_NAME}"; then
-    logFatal "Failed to create pool"
+    logError "Failed to create pool"
     return 1
   fi
 
@@ -46,12 +46,12 @@ install_truenas() {
   local truenas_res
 
   if ! config_load "${SDQ_ROOT}/external/demers-qnap/data/local.env"; then
-    logFatal "Failed to load local configuration"
+    logError "Failed to load local configuration"
     return 1
   fi
 
   if [[ -z "${XCP_CRITICAL_TAG}" ]]; then
-    logFatal "XCP_CRITICAL_TAG is not set. Did you load local.env?"
+    logError "XCP_CRITICAL_TAG is not set. Did you load local.env?"
     return 1
   fi
 
@@ -81,23 +81,23 @@ install_truenas() {
 }
 
 update_plugin() {
-  local start_file stop_file
-  start_file="${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap/start_halley"
-  stop_file="${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap//stop_halley"
-
   if [[ -z "${PLUGIN_DIR}" ]]; then
-    logFatal "No plugin directory set"
+    logError "No plugin directory set"
     return 1
   elif [[ -z "${QNAP_HOME}" ]]; then
-    logFatal "QNAP_HOME is not set"
-    return 1
-  elif [[ ! -f "${start_file}" ]]; then
-    logFatal "Start plugin file not found"
-    return 1
-  elif [[ ! -f "${stop_file}" ]]; then
-    logFatal "Stop plugin file not found"
+    logError "QNAP_HOME is not set"
     return 1
   fi
+
+  # Find plugin files
+  local files=()
+  local file
+  for file in "${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap/plugins/"*; do
+    # Only keep files that start with start_, stop_ and power_
+    if [[ $(basename "${file}") =~ ^(start_|stop_|power_).* ]]; then
+      files+=("${file}")
+    fi
+  done
 
   # Determine plugin directory
   local plugin_dir git_root file_name tmp_file
@@ -114,7 +114,7 @@ update_plugin() {
 
   # Configure the plugin
   local plug_file
-  for plug_file in "${start_file}" "${stop_file}"; do
+  for plug_file in "${files[@]}"; do
     file_name=$(basename "${plug_file}")
     if ! tmp_file=$(mktemp); then
       logError "Failed to create temporary file"
@@ -130,7 +130,7 @@ update_plugin() {
     # Install plugin
     local uri cmd res
     uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
-    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
+    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_USER}" "${XEN_PWD}" "force"; then
       logError "Failed to upload start plugin"
       return 1
     elif ! rm "${tmp_file}"; then
@@ -185,7 +185,7 @@ mount_truenas_iso() {
 
 configure_network() {
   if ! xe_cleanup_network; then
-    logFatal "Failed to cleanup networks"
+    logError "Failed to cleanup networks"
     return 1
   fi
 
@@ -199,7 +199,7 @@ configure_network() {
   logInfo "Network NIC: ${NET_NIC} (${net_mac})"
 
   if ! xe_vlan_config "${net_mac}" "${NETS}"; then
-    logFatal "Failed to configure network interface"
+    logError "Failed to configure network interface"
     return 1
   fi
 
@@ -213,7 +213,7 @@ configure_network() {
 
   # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
   if ! xe_create_connection "${XEN_HOST}"; then
-    logFatal "Failed to connect to demers-qnap"
+    logError "Failed to connect to demers-qnap"
     return 1
   else
     logInfo "Connected successfully to demers-qnap"
@@ -252,7 +252,7 @@ sdq_config() {
   done
 
   if [[ -z "${DIR_QNAP}" ]]; then
-    logFatal "DIR_QNAP is not set"
+    logError "DIR_QNAP is not set"
     return 1
   fi
 
@@ -289,7 +289,7 @@ sdq_config() {
 
   # Test connection to the management interface of demers-qnap
   if ! xe_create_connection "${XEN_MGT}"; then
-    logFatal "Failed to connect to demers-qnap's management interface"
+    logError "Failed to connect to demers-qnap's management interface"
     return 1
   else
     logInfo "Connected successfully to demers-qnap's management interface"
@@ -297,57 +297,57 @@ sdq_config() {
 
   # Load hardware configuration
   if ! config_load "${DIR_QNAP}/data/hardware.env"; then
-    logFatal "Failed to load hardware configuration"
+    logError "Failed to load hardware configuration"
     return 1
   fi
 
   if [[ -z "${XEN_HOST}" ]]; then
-    logFatal "XEN_HOST is not set"
+    logError "XEN_HOST is not set"
     return 1
   elif [[ -z "${XEN_USER}" ]]; then
-    logFatal "XEN_USER is not set"
+    logError "XEN_USER is not set"
     return 1
   elif [[ -z "${XEN_PWD}" ]]; then
-    logFatal "XEN_PWD is not set"
+    logError "XEN_PWD is not set"
     return 1
   elif [[ -z "${XEN_ISO_USER}" ]]; then
-    logFatal "XEN_ISO_USER is not set"
+    logError "XEN_ISO_USER is not set"
     return 1
   elif [[ -z "${XEN_ISO_PWD}" ]]; then
-    logFatal "XEN_ISO_PWD is not set"
+    logError "XEN_ISO_PWD is not set"
     return 1
   elif [[ -z "${XEN_MGT}" ]]; then
-    logFatal "XEN_MGT is not set"
+    logError "XEN_MGT is not set"
     return 1
   elif [[ -z "${XEN_GW}" ]]; then
-    logFatal "XEN_GW is not set"
+    logError "XEN_GW is not set"
     return 1
   elif [[ -z "${MGT_NIC}" ]]; then
-    logFatal "MGT_NIC is not set"
+    logError "MGT_NIC is not set"
     return 1
   elif [[ -z "${NET_NIC}" ]]; then
-    logFatal "NET_NIC is not set"
+    logError "NET_NIC is not set"
     return 1
   elif [[ -z "${NETS}" ]]; then
-    logFatal "NETS is not set"
+    logError "NETS is not set"
     return 1
   elif [[ -z "${VM_NAME_NAS}" ]]; then
-    logFatal "VM_NAME_NAS is not set"
+    logError "VM_NAME_NAS is not set"
     return 1
   elif [[ -z "${VM_RAM_NAS}" ]]; then
-    logFatal "VM_RAM_NAS is not set"
+    logError "VM_RAM_NAS is not set"
     return 1
   elif [[ -z "${VM_VCPUS_NAS}" ]]; then
-    logFatal "VM_VCPUS_NAS is not set"
+    logError "VM_VCPUS_NAS is not set"
     return 1
   elif [[ -z "${VM_DISK_NAS}" ]]; then
-    logFatal "VM_DISK_NAS is not set"
+    logError "VM_DISK_NAS is not set"
     return 1
   elif [[ -z "${VM_NET_NAS}" ]]; then
-    logFatal "VM_NET_NAS is not set"
+    logError "VM_NET_NAS is not set"
     return 1
   elif [[ -z "${POOL_NAME}" ]]; then
-    logFatal "POOL_NAME is not set"
+    logError "POOL_NAME is not set"
     return 1
   fi
 }
diff --git a/src/bootstrap/00-baremetal/demers-sol/setup b/src/bootstrap/00-baremetal/demers-sol/setup
--- a/src/bootstrap/00-baremetal/demers-sol/setup
+++ b/src/bootstrap/00-baremetal/demers-sol/setup
@@ -22,23 +22,19 @@ setup() {
   if ! sdq_config; then
     logError "Failed to configure"
     return 1
-  fi
-
-  if ! configure_network; then
+  elif ! configure_network; then
     logError "Failed to configure network"
     return 1
+  elif ! configure_htpc; then
+    logError "Failed to configure HTPC"
+    return 1
+  elif ! connect_qnap_to_sol; then
+    logError "Failed to connect QNAP"
+    return 1
+  elif ! join_pool; then
+    logError "Failed to join pool"
+    return 1
   fi
-
-  # # Create the pool if it doesn't exist already
-  # if ! xe_pool_create "${POOL_NAME}"; then
-  #   logFatal "Failed to create pool"
-  #   return 1
-  # fi
-
-  # Start TrueNAS installation
-  # if ! install_truenas; then
-  #   return 1
-  # fi
 
   logInfo "Finished executing properly"
 }
@@ -101,6 +97,150 @@ configure_network() {
   done
 }
 
+configure_htpc() {
+  if ! xe_vm_prepare "${HTPC_VM_NAME}" "${HTPC_VM_RAM}" "${HTPC_VM_VCPUS}" "${HTPC_VM_DISK}"; then
+    logError "Failed to prepare ${HTPC_VM_NAME} VM"
+    return 1
+  elif ! xe_vm_net_attach "${HTPC_VM_NAME}" "${HTPC_VM_NET}"; then
+    logError "Failed to attach network to VM"
+    return 1
+  elif ! xe_vm_pci_attach "${HTPC_VM_NAME}" "${PCI_GPU}"; then
+    logError "Failed to attach PCI device to VM"
+    return 1
+  elif ! htpc_usb_mount; then
+    logError "Failed to setup USB passthrough"
+    return 1
+  elif ! xe_vm_start "${HTPC_VM_NAME}"; then
+    logError "Failed to start ${HTPC_VM_NAME}"
+    return 1
+  elif ! install_htpc_pugins; then
+    return 1
+  else
+    logInfo "HTPC Ready to install"
+  fi
+
+  return 0
+}
+
+install_htpc_pugins() {
+  # Find plugin files
+  local files=()
+  local file
+  for file in "${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-sol/plugins/"*; do
+    # Only keep files that start with start_, stop_ and power_
+    if [[ $(basename "${file}") =~ ^(start_|stop_|power_).* ]]; then
+      files+=("${file}")
+    fi
+  done
+
+  # Determine plugin directory
+  local plugin_dir git_root file_name tmp_file
+  plugin_dir=${PLUGIN_DIR}
+  cf_git_find_root git_root "${SDQ_SCRIPT}"
+
+  # Get plugin_dir relative to git_root
+  plugin_dir="${plugin_dir#"${git_root}"}"
+  plugin_dir="${plugin_dir#/}"
+
+  # Make it absolute to demers-sol
+  plugin_dir="${SOL_HOME}/${plugin_dir}"
+  logInfo "Plugin directory: ${plugin_dir}"
+
+  # Configure the plugin
+  local plug_file
+  # shellcheck disable=SC2066
+  for plug_file in "${files[@]}"; do
+    file_name=$(basename "${plug_file}")
+    if ! tmp_file=$(mktemp); then
+      logError "Failed to create temporary file"
+      return 1
+    elif ! cp "${plug_file}" "${tmp_file}"; then
+      logError "Failed to copy start plugin file"
+      return 1
+    elif ! env_replace_in_place "${tmp_file}"; then
+      logError "Failed to replace env variables in start plugin file"
+      return 1
+    fi
+
+    # Install plugin
+    local uri cmd res
+    uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
+    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_USER}" "${XEN_PWD}" "force"; then
+      logError "Failed to upload start plugin"
+      return 1
+    elif ! rm "${tmp_file}"; then
+      logError "Failed to remove temporary file"
+      return 1
+    fi
+
+    # Make the plugin executable
+    cmd=(chmod +x "${plugin_dir}/${file_name}")
+    if ! sol_exec res "${cmd[@]}"; then
+      logError "Failed to make start plugin executable"
+      return 1
+    fi
+  done
+}
+
+connect_qnap_to_sol() {
+  # Get demers identity
+  local demers_id
+  if ! ssh_identity_create demers_id "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" 22; then
+    logError "Failed to create demers identity"
+    return 1
+  fi
+
+  # Need qnap config
+  if ! source "${SDQ_ROOT}/.config/demers-qnap.env"; then
+    logError "Failed to load QNAP configuration"
+    return 1
+  fi
+
+  local myres
+  ssh_identity_authorize "${demers_id}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" 22
+  myres=$?
+
+  # Restore sol config
+  if ! source "${SDQ_ROOT}/.config/demers-sol.env"; then
+    logError "Failed to load demers-sol configuration"
+    return 1
+  fi
+
+  return "${myres}"
+}
+
+join_pool() {
+  # TODO: Implement
+  return 0
+}
+
+sol_exec() {
+  local __ssh_res=${1}
+  shift
+
+  nu_ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" "22" "${@}"
+  return $?
+}
+
+htpc_usb_mount() {
+  local htpc_usb_devices
+  IFS="," read -r -a htpc_usb_devices <<<"${USB_DEVICES}"
+
+  local var_usb_vid var_usb_pid var_usb_sn
+  for device in "${htpc_usb_devices[@]}"; do
+    var_usb_vid="UDEV_VID_${device}"
+    var_usb_pid="UDEV_PID_${device}"
+    var_usb_sn="UDEV_SN_${device}"
+
+    if xe_vm_usb_attach "${HTPC_VM_NAME}" "${!var_usb_vid}" "${!var_usb_pid}" "${!var_usb_sn}"; then
+      logInfo "Attached USB device ${device} to ${HTPC_VM_NAME}"
+    else
+      logError "Failed to attach USB device ${device} to ${HTPC_VM_NAME}"
+      return 1
+    fi
+  done
+}
+
 sdq_config() {
   # Determine BPKG's global prefix
   if [[ -z "${PREFIX}" ]]; then
@@ -135,6 +275,9 @@ sdq_config() {
     return 1
   elif [[ -z "${DIR_SOL}" ]]; then
     logError "DIR_SOL is not set"
+    return 1
+  elif [[ -z "${SOL_HOME}" ]]; then
+    logError "SOL_HOME is not set"
     return 1
   elif ! source "${DIR_XAPI}/src/xe_vm.sh"; then
     logError "Failed to load xe_vm.sh"
@@ -212,6 +355,30 @@ sdq_config() {
   elif [[ -z "${POOL_NAME}" ]]; then
     logError "POOL_NAME is not set"
     return 1
+  elif [[ -z "${HTPC_VM_NAME}" ]]; then
+    logError "HTPC_VM_NAME is not set"
+    return 1
+  elif [[ -z "${HTPC_VM_RAM}" ]]; then
+    logError "HTPC_VM_RAM is not set"
+    return 1
+  elif [[ -z "${HTPC_VM_VCPUS}" ]]; then
+    logError "HTPC_VM_VCPUS is not set"
+    return 1
+  elif [[ -z "${HTPC_VM_DISK}" ]]; then
+    logError "HTPC_VM_DISK is not set"
+    return 1
+  elif [[ -z "${HTPC_VM_NET}" ]]; then
+    logError "HTPC_VM_NET is not set"
+    return 1
+  elif [[ -z "${PCI_GPU}" ]]; then
+    logError "PCI_GPU is not set"
+    return 1
+  elif [[ -z "${USB_DEVICES}" ]]; then
+    logError "USB_DEVICES is not set"
+    return 1
+  elif [[ -z "${PLUGIN_DIR}" ]]; then
+    logError "PLUGIN_DIR is not set"
+    return 1
   fi
 }
 
@@ -221,7 +388,7 @@ LOCAL_CONFIG=".config/demers.env:.config/demers-sol.env:.config/local.env"
 ###########################
 ###### Startup logic ######
 ###########################
-# SDQ_SCRIPT="${0}"
+SDQ_SCRIPT="${0}"
 
 # Get directory of this script
 # https://stackoverflow.com/a/246128
