Try adding a stop_halley plugin

diff --git a/src/bootstrap/00-baremetal/demers-qnap/setup b/src/bootstrap/00-baremetal/demers-qnap/setup
--- a/src/bootstrap/00-baremetal/demers-qnap/setup
+++ b/src/bootstrap/00-baremetal/demers-qnap/setup
@@ -113,35 +113,38 @@ update_plugin() {
   logInfo "Plugin directory: ${plugin_dir}"
 
   # Configure the plugin
-  file_name=$(basename "${start_file}")
-  if ! tmp_file=$(mktemp); then
-    logError "Failed to create temporary file"
-    return 1
-  elif ! cp "${start_file}" "${tmp_file}"; then
-    logError "Failed to copy start plugin file"
-    return 1
-  elif ! env_replace_in_place "${tmp_file}"; then
-    logError "Failed to replace env variables in start plugin file"
-    return 1
-  fi
+  local plug_file
+  for plug_file in "${start_file}" "${stop_file}"; do
+    file_name=$(basename "${plug_file}")
+    if ! tmp_file=$(mktemp); then
+      logError "Failed to create temporary file"
+      return 1
+    elif ! cp "${plug_file}" "${tmp_file}"; then
+      logError "Failed to copy start plugin file"
+      return 1
+    elif ! env_replace_in_place "${tmp_file}"; then
+      logError "Failed to replace env variables in start plugin file"
+      return 1
+    fi
 
-  # Install plugin
-  local uri cmd res
-  uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
-  if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
-    logError "Failed to upload start plugin"
-    return 1
-  elif ! rm "${tmp_file}"; then
-    logError "Failed to remove temporary file"
-    return 1
-  fi
+    # Install plugin
+    local uri cmd res
+    uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
+    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
+      logError "Failed to upload start plugin"
+      return 1
+    elif ! rm "${tmp_file}"; then
+      logError "Failed to remove temporary file"
+      return 1
+    fi
 
-  # Make the plugin executable
-  cmd=(chmod +x "${plugin_dir}/${file_name}")
-  if ! qnap_exec res "${cmd[@]}"; then
-    logError "Failed to make start plugin executable"
-    return 1
-  fi
+    # Make the plugin executable
+    cmd=(chmod +x "${plugin_dir}/${file_name}")
+    if ! qnap_exec res "${cmd[@]}"; then
+      logError "Failed to make start plugin executable"
+      return 1
+    fi
+  done
 
   # Exexute the plugin to start the VM
   cmd=("${plugin_dir}/${file_name}")
diff --git a/src/bootstrap/00-baremetal/demers-qnap/stop_halley b/src/bootstrap/00-baremetal/demers-qnap/stop_halley
--- a/src/bootstrap/00-baremetal/demers-qnap/stop_halley
+++ b/src/bootstrap/00-baremetal/demers-qnap/stop_halley
@@ -5,8 +5,43 @@
 
 plugin_halley_stop() {
   logInfo "Stopping Halley"
-  return 0
+
+  if ! config_load; then
+    return 1
+  fi
+  if ! xe_vm_shutdown "${NAS_VM_NAME}" "force"; then
+    logError "Failed to shutdown VM"
+    return 1
+  fi
 }
+
+config_load() {
+
+  # shellcheck disable=SC1091
+  if ! config_load "${SHH_ROOT}/data/local.env"; then
+    return 1
+  elif [[ -z "${CONFIG_DIR}" ]]; then
+    logError "CONFIG_DIR is not set"
+    return 1
+  elif [[ -z "${XAPI_DIR}" ]]; then
+    logError "XAPI_DIR is not set"
+    return 1
+  elif ! source "${XAPI_DIR}/src/xe_vm.sh"; then
+    logError "Failed to load xe_vm.sh"
+    return 1
+  else
+    NAS_VM_SR="${!NAS_VM_SR}"
+    if [[ -z "${NAS_VM_SR}" ]]; then
+      logError "NAS_VM_SR is not set"
+      return 1
+    elif [[ -z "${DRIVE_MAX}" ]]; then
+      logError "DRIVE_MAX is not set"
+      return 1
+    fi
+  fi
+}
+
+NAS_VM_NAME="@VM_NAME_NAS@"
 
 ###########################
 ###### Startup logic ######
@@ -37,6 +72,10 @@ fi
 if ! source "${PREFIX}/lib/slf4.sh"; then
   echo "Failed to import slf4.sh"
   exit 1
+fi
+# shellcheck disable=SC1091
+if ! source "${PREFIX}/lib/config.sh"; then
+  logFatal "Failed to import config.sh"
 fi
 
 if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
